export let quotes = [
  "'All our dreams can come true, if we have the courage to pursue them.' —Walt Disney",
  "'The secret of getting ahead is getting started.' —Mark Twain",
  "'The best time to plant a tree was 20 years ago.The second best time is now.' ―Chinese Proverb",
  "'Only the paranoid survive.' —Andy Grove",
  "'It’s hard to beat a person who never gives up.' —Babe Ruth",
  "'I wake up every morning and think to myself, ‘How far can I push this company in the next 24 hours.' —Leah Busque",
  "'If people are doubting how far you can go, go so far that you can’t hear them anymore.' —Michele Ruiz",
  "'Write it.Shoot it.Publish it.Crochet it.Sauté it.Whatever.MAKE.' —Joss Whedon",
  "'The same boiling water that softens the potato hardens the egg. It’s what you’re made of. Not the circumstances.' —Unknown",
  "'If we have the attitude that it’s going to be a great day it usually is.' —Catherine Pulsifier",
  "'You can either experience the pain of discipline or the pain of regret. The choice is yours.' —Unknown",
  "'Impossible is just an opinion.' —Paulo Coelho",
  "'Your passion is waiting for your courage to catch up.' —Isabelle Lafleche",
  "'Magic is believing in yourself. If you can make that happen, you can make anything happen.' —Johann Wolfgang Von Goethe",
  "'If something is important enough, even if the odds are stacked against you, you should still do it.' —Elon Musk",
  "'Hold the vision, trust the process.' —Unknown",
  "'Don’t be afraid to give up the good to go for the great.' —John D. Rockefeller",
  "'People who wonder if the glass is half empty or full miss the point. The glass is refillable.' —Unknown",
]
